deploy: Add environment and file checks to Makefile.
- Include .env file and define a list of required environment variables.
- Add `check-env` target to validate that the .env file exists and that all
  required variables are set.
- Add `check-gadm-file` target to ensure the specified GADM file exists.
- Integrate these checks into the `build`, `init-db`, and `reinit-db` targets
  for better error handling and validation.

Signed-off-by: Nikolay Martyanov <ohmspectator@gmail.com>

diff --git a/deployment/Makefile b/deployment/Makefile
--- a/deployment/Makefile
+++ b/deployment/Makefile
@@ -1,8 +1,28 @@
 # Name of the Docker Compose project
 PROJECT_NAME = tyr_postgis
 
+include .env
+
+REQUIRED_ENV_VARS = POSTGRES_DB POSTGRES_USER POSTGRES_PASSWORD GADM_FILE
+
+check-env:
+	@if [ ! -f .env ]; then \
+		echo "Error: .env file is missing. Initialize it from .env.example."; \
+		exit 1; \
+	fi
+	@for var in $(REQUIRED_ENV_VARS); do \
+		awk -F '=' -v key="$$var" '$$1 == key { if ($$2 == "" || $$2 == "<set_your_db_name>" || $$2 == "<set_your_db_user>" || $$2 == "<set_your_db_password>" || $$2 == "<set_path_to_your_gadm_file>") exit 1 }' .env || { echo "Error: $$var is not set or empty in .env"; exit 1; }; \
+	done
+
+# Check the GADM file path
+check-gadm-file:
+	@if [ ! -f $(GADM_FILE) ]; then \
+		echo "Error: GADM file is missing. Set the correct path to the GADM file in .env."; \
+		exit 1; \
+	fi
+
 # Build the Docker image using docker-compose
-build:
+build: check-env
 	docker-compose build
 
 # Run the Docker container using docker-compose and forward the PostgreSQL port
@@ -10,11 +30,11 @@ run:
 	docker-compose up -d
 
 # Initialize the PostGIS database and import GPKG file
-init-db: build run
+init-db: check-gadm-file build run
 	@echo "Database initialized and GPKG file imported."
 
 # Forcefully re-initialize the database
-reinit-db: clean-volume init-db
+reinit-db: check-gadm-file clean-volume init-db
 	@echo "Database forcefully re-initialized."
 
 # Stop and remove the Docker container
